"""add room devices

Revision ID: 3e87d73fbc47
Revises: 9a0d8ccea5b0
Create Date: 2026-01-19 21:57:27.164922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e87d73fbc47'
down_revision: Union[str, None] = '9a0d8ccea5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # room_satellites was introduced in a pre-baseline migration that's no longer in the tree,
    # so fresh DBs never had it. Make the teardown idempotent.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'room_satellites' in inspector.get_table_names():
        existing = {ix['name'] for ix in inspector.get_indexes('room_satellites')}
        if 'ix_room_satellites_id' in existing:
            op.drop_index('ix_room_satellites_id', table_name='room_satellites')
        if 'ix_room_satellites_satellite_id' in existing:
            op.drop_index('ix_room_satellites_satellite_id', table_name='room_satellites')
        op.drop_table('room_satellites')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_satellites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('satellite_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_connected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='room_satellites_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_satellites_pkey')
    )
    op.create_index('ix_room_satellites_satellite_id', 'room_satellites', ['satellite_id'], unique=True)
    op.create_index('ix_room_satellites_id', 'room_satellites', ['id'], unique=False)
    # ### end Alembic commands ###
